name: medapp
description: A medical report management application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  # google_mlkit_digital_ink_recognition: ^0.13.0
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_language_id: ^0.12.0
  google_mlkit_translation: ^0.12.0
  speech_to_text: ^7.0.0
  share_plus: ^10.1.4
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  get_it: ^8.0.3
  timezone: ^0.10.0
  translator: ^1.0.3+1
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  google_generative_ai: ^0.3.0
  signature: ^5.4.0
  flutter_signature_pad: ^3.0.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  animated_notch_bottom_bar: ^1.0.3
  html: ^0.15.4
  webview_flutter: ^4.4.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.1
  printing: ^5.14.2
  path_provider: ^2.1.2
  flutter_email_sender: ^6.0.2
  cached_network_image: ^3.3.0
  http_parser: ^4.1.2
  pdf: ^3.10.7
  flutter_downloader: ^1.10.2
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  connectivity_plus: ^4.0.2
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^9.1.0
  camera: 0.12.0
  logging: ^1.2.0
  shared_preferences: ^2.5.2
  intl_phone_field: ^3.2.0
  path: any
  bloc: ^9.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
